#!/bin/bash

# ==============================================================================
# Copy this as a template for ./dialyze scripts, when ./dialyze_basic fails.
# ==============================================================================

. ../../dialyze_common
