#!/bin/bash

. ../../make_common

ERL_LIBS=$(pwd):$ERL_LIBS
cd code
sed -i 's.n2o/include.code/include.' src/*.erl src/*/*.erl src/*/*/*.erl
basic_rebar
sed -i 's.code/include.n2o/include.' src/*.erl src/*/*.erl src/*/*/*.erl
